services:
  - type: web
    name: pharmanps-aloucoding
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: "./build.sh"
    startCommand: "gunicorn pharmanps_alou.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        value: "postgresql://pharmanps_alou_user:k8mNXP17K2LQVbjdeNMoFAFSPqGo4L5f@dpg-d3s7m1ruibrs73enh090-a/pharmanps_alou"
