# Generated by Django 5.2.7 on 2025-10-19 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom commercial')),
                ('dci', models.CharField(help_text='Dénomination Commune Internationale', max_length=200, verbose_name='DCI')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='Code-barres')),
                ('form', models.CharField(choices=[('comprimé', 'Comprimé'), ('gélule', 'Gélule'), ('sirop', 'Sirop'), ('injection', 'Injection'), ('inhalateur', 'Inhalateur'), ('pommade', 'Pommade'), ('crème', 'Crème'), ('suppositoire', 'Suppositoire'), ('collyre', 'Collyre'), ('solution', 'Solution')], max_length=50, verbose_name='Forme galénique')),
                ('dosage', models.CharField(help_text='Ex: 500mg, 10ml', max_length=100, verbose_name='Dosage')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat")),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantité en stock')),
                ('min_quantity', models.IntegerField(default=10, help_text="Seuil d'alerte", verbose_name='Stock minimum')),
                ('expiry_date', models.DateField(verbose_name='Date de péremption')),
                ('location', models.CharField(blank=True, help_text='Rayon, étagère...', max_length=100, null=True, verbose_name='Emplacement')),
                ('requires_prescription', models.BooleanField(default=False, verbose_name='Prescription requise')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medications/', verbose_name='Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='medications.category', verbose_name='Catégorie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entrée', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement'), ('retour', 'Retour'), ('perte', 'Perte'), ('périmé', 'Périmé')], max_length=20, verbose_name='Type de mouvement')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Raison/Justification')),
                ('reference', models.CharField(blank=True, help_text='Numéro de bon, facture...', max_length=100, null=True, verbose_name='Référence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='medications.medication', verbose_name='Médicament')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
