# Generated by Django 5.2.7 on 2025-10-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('completee', 'Complétée'), ('annulee', 'Annulée')], default='en_cours', max_length=20, verbose_name='Statut'),
        ),
    ]
